### ISSUE TITLE
compile on musl based Alpine linux

### ISSUE THREAD

**Issue by debiansid** [icpz/snell-server-reversed#1]
Is it possible to achieve that?

thanks

**Comment by icpz** [comment]
Sure, I'll adapt it when I'm available.

But I don't recommend to build this project for a real snell service since this piece of code is just a demo.

If you really need an opensource port of snell server, please let me know. I'll start a new project for it.

**Comment by debiansid** [comment]
Thank you Sir! I need it running on alpine Linux. But it's very likely the original developer would not do it.

**Comment by icpz** [comment]
Hi, I made a new repo [here](https://github.com/icpz/open-snell).

But it only supports latest surge client.

If you have any questions please open issues there or email me.
