### ISSUE TITLE
snell v3 has been released, any plan to support it?

### ISSUE THREAD

**Issue by XenMe** [icpz/snell-server-reversed#2]
as subjected, snell v3 is a major update added UDP support, will there any plan to upgrade to v3?

**Comment by icpz** [comment]
Let's wait for the official release version, and I'll try my best.

**Comment by icpz** [comment]
Hi, I've updated UDP over TCP protocol added by snell v3.

**Comment by gengjiawen** [comment]
v4 released: https://manual.nssurge.com/others/snell.html

**Comment by icpz** [comment]
I'm recently very busy, but reversing v4 is under planning.

**Comment by feewg** [comment]
v5 released https://kb.nssurge.com/surge-knowledge-base/zh/release-notes/snell
